//! Contains all structures necessary to work with classfile objects
//! A classfile object is a binary file generated by a Java Virtual Machine language compiler

// Re-export modules to make it easy to use for any code outside of this module
pub use attribute::*;
pub use class_file::*;
pub use constant_pool::*;
pub use field::*;
pub use method::*;

mod attribute;
mod class_file;
mod constant_pool;
mod field;
mod method;
