use crate::utils::bitmask_matches;

use super::Flags;

/// Method access and property flags
// TODO: remove debug directive
#[derive(Debug, PartialEq)]
pub enum MethodAccessFlags {
    /// Declared public; may be accessed from outside its package
    AccPublic,

    /// Declared private; accessible only within the defining class and other classes belonging to the same nest [§5.4.4](https://docs.oracle.com/javase/specs/jvms/se17/html/jvms-5.html#jvms-5.4.4)
    AccPrivate,

    /// Declared protected; may be accessed within subclasses
    AccProtected,

    /// Declared static
    AccStatic,

    /// Declared final; must not be overridden [§5.4.5](https://docs.oracle.com/javase/specs/jvms/se17/html/jvms-5.html#jvms-5.4.5)
    AccFinal,

    /// Declared synchronized; invocation is wrapped by a monitor use
    AccSynchronized,

    /// A bridge method, generated by the compiler
    AccBridge,

    /// Declared with variable number of arguments
    AccVarArgs,

    /// Declared native; implemented in a language other than the Java programming language
    AccNative,

    /// Declared abstract; no implementation is provided
    AccAbstract,

    /// In a class file whose major version number is at least 46 and at most 60: Declared strictfp
    AccStrict,

    /// Declared synthetic; not present in the source code
    AccSynthetic,
}

impl Flags for MethodAccessFlags {
    type AccessFlagType = MethodAccessFlags;

    fn from_u16(value: u16) -> Vec<Self::AccessFlagType> {
        let mut flags = vec![];

        if bitmask_matches(value, 0x0001) {
            flags.push(Self::AccPublic);
        }

        if bitmask_matches(value, 0x0002) {
            flags.push(Self::AccPrivate);
        }

        if bitmask_matches(value, 0x0004) {
            flags.push(Self::AccProtected);
        }

        if bitmask_matches(value, 0x0008) {
            flags.push(Self::AccStatic);
        }

        if bitmask_matches(value, 0x0010) {
            flags.push(Self::AccFinal);
        }

        if bitmask_matches(value, 0x0020) {
            flags.push(Self::AccSynchronized);
        }

        if bitmask_matches(value, 0x0040) {
            flags.push(Self::AccBridge);
        }

        if bitmask_matches(value, 0x0080) {
            flags.push(Self::AccVarArgs);
        }

        if bitmask_matches(value, 0x0100) {
            flags.push(Self::AccNative);
        }

        if bitmask_matches(value, 0x0400) {
            flags.push(Self::AccAbstract);
        }

        if bitmask_matches(value, 0x0800) {
            flags.push(Self::AccStrict);
        }

        if bitmask_matches(value, 0x1000) {
            flags.push(Self::AccSynthetic);
        }

        assert!(flags.len() > 0, "Bitmask does not specify ANY access flags");
        flags
    }
}

mod tests {
    use super::Flags;
    use super::MethodAccessFlags;

    #[test]
    fn test_method_access_flag_public() {
        assert_eq!(
            MethodAccessFlags::from_u16(0x0001)[0],
            MethodAccessFlags::AccPublic,
            "Incorrect access flag returned"
        );
    }

    #[test]
    fn test_method_access_flag_private() {
        assert_eq!(
            MethodAccessFlags::from_u16(0x0002)[0],
            MethodAccessFlags::AccPrivate,
            "Incorrect access flag returned"
        );
    }

    #[test]
    fn test_method_access_flag_protected() {
        assert_eq!(
            MethodAccessFlags::from_u16(0x0004)[0],
            MethodAccessFlags::AccProtected,
            "Incorrect access flag returned"
        );
    }

    #[test]
    fn test_method_access_flag_static() {
        assert_eq!(
            MethodAccessFlags::from_u16(0x0008)[0],
            MethodAccessFlags::AccStatic,
            "Incorrect access flag returned"
        );
    }

    #[test]
    fn test_method_access_flag_final() {
        assert_eq!(
            MethodAccessFlags::from_u16(0x0010)[0],
            MethodAccessFlags::AccFinal,
            "Incorrect access flag returned"
        );
    }

    #[test]
    fn test_method_access_flag_synchronized() {
        assert_eq!(
            MethodAccessFlags::from_u16(0x0020)[0],
            MethodAccessFlags::AccSynchronized,
            "Incorrect access flag returned"
        );
    }

    #[test]
    fn test_method_access_flag_bridge() {
        assert_eq!(
            MethodAccessFlags::from_u16(0x0040)[0],
            MethodAccessFlags::AccBridge,
            "Incorrect access flag returned"
        );
    }

    #[test]
    fn test_method_access_flag_varargs() {
        assert_eq!(
            MethodAccessFlags::from_u16(0x0080)[0],
            MethodAccessFlags::AccVarArgs,
            "Incorrect access flag returned"
        );
    }

    #[test]
    fn test_method_access_flag_native() {
        assert_eq!(
            MethodAccessFlags::from_u16(0x0100)[0],
            MethodAccessFlags::AccNative,
            "Incorrect access flag returned"
        );
    }

    #[test]
    fn test_method_access_flag_abstract() {
        assert_eq!(
            MethodAccessFlags::from_u16(0x0400)[0],
            MethodAccessFlags::AccAbstract,
            "Incorrect access flag returned"
        );
    }

    #[test]
    fn test_method_access_flag_strict() {
        assert_eq!(
            MethodAccessFlags::from_u16(0x0800)[0],
            MethodAccessFlags::AccStrict,
            "Incorrect access flag returned"
        );
    }

    #[test]
    fn test_method_access_flag_synthetic() {
        assert_eq!(
            MethodAccessFlags::from_u16(0x1000)[0],
            MethodAccessFlags::AccSynthetic,
            "Incorrect access flag returned"
        );
    }

    #[test]
    fn test_method_access_multiple_flags() {
        assert_eq!(
            MethodAccessFlags::from_u16(0x1533),
            vec![
                MethodAccessFlags::AccPublic,
                MethodAccessFlags::AccPrivate,
                MethodAccessFlags::AccFinal,
                MethodAccessFlags::AccSynchronized,
                MethodAccessFlags::AccNative,
                MethodAccessFlags::AccAbstract,
                MethodAccessFlags::AccSynthetic,
            ],
            "Incorrect access flags returned"
        );
    }
}
